# -*- coding: utf-8 -*-
"""BMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4wdmILZKW99EHVrCR1Da1V9mSYPGWZG
"""

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

list(uploaded.keys())

df = pd.read_csv('EV_Battery_Charging_TR_Dataset_with_Notes.csv')
print(df.shape)
df.head()

df.info()
df.isnull().sum()

print(df["BMS_Status"].value_counts())
print(df["BMS_Status"].unique())
print(df["ChargingStage"].unique())
print(df["MoistureDetected"].unique())
print(df["EventFlag"].unique())

df = df.drop(columns=[
    "Timestamp",
    "ChargerID",
    "CellID",
    "Notes"
])
print(df.columns)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
categorical_columns = [
    "ChargingStage",
    "BMS_Status",
    "EventFlag"
]

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])
df["MoistureDetected"] = df["MoistureDetected"].astype(int)

df.head()

df.info()

X = df.drop(columns=["BMS_Status"])
y = df["BMS_Status"]
print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

print(X_scaled.min())
print(X_scaled.max())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

num_particles = 25
num_features = X_train.shape[1]
max_iterations = 50

print("Particles:", num_particles)
print("Features :", num_features)
print("Iterations:", max_iterations)

particles = np.random.randint(
    0,
    2,
    size=(num_particles, num_features)
)
print(particles)
print(particles.shape)

selected_features = particles.sum(axis=1)

print(selected_features)

particle_number = 0

print("Particle:", particle_number + 1)
print(particles[particle_number])

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score

def fitness_function(particle, X_train, X_test, y_train, y_test):

    selected = particle.astype(bool)
    if np.sum(selected) == 0:
        return np.inf, 0, 0, 0

    X_train_selected = X_train.loc[:, selected]
    X_test_selected = X_test.loc[:, selected]

    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train_selected, y_train)


    predictions = knn.predict(X_test_selected)

    accuracy = accuracy_score(y_test, predictions)
    macro_f1 = f1_score(y_test, predictions, average="macro")

    num_selected = np.sum(selected)

    penalty = 0.1 * (num_selected / num_features)

    fitness = -((accuracy + macro_f1) / 2) + penalty

    return fitness, accuracy, macro_f1, num_selected


fitness, accuracy, macro_f1, num_selected = fitness_function(
    particles[0],
    X_train,
    X_test,
    y_train,
    y_test
)

print("Fitness:", fitness)
print("Accuracy:", accuracy)
print("Macro F1:", macro_f1)
print("Selected Features:", num_selected)

fitness_values = []
accuracies = []
macro_f1_scores = []
selected_feature_counts = []

for particle in particles:
    fitness, accuracy, macro_f1, num_selected = fitness_function(
        particle,
        X_train,
        X_test,
        y_train,
        y_test
    )

    fitness_values.append(fitness)
    accuracies.append(accuracy)
    macro_f1_scores.append(macro_f1)
    selected_feature_counts.append(num_selected)

fitness_values = np.array(fitness_values)
accuracies = np.array(accuracies)
macro_f1_scores = np.array(macro_f1_scores)
selected_feature_counts = np.array(selected_feature_counts)

results = pd.DataFrame({
    "Fitness": fitness_values,
    "Accuracy": accuracies,
    "Macro F1": macro_f1_scores,
    "Selected Features": selected_feature_counts
})

results

pbest_particles = particles.copy()
pbest_fitness = fitness_values.copy()

gbest_index = np.argmin(fitness_values)

gbest_particle = particles[gbest_index].copy()
gbest_fitness = fitness_values[gbest_index]

print("Best Particle Index :", gbest_index)
print("Best Fitness        :", gbest_fitness)
print("Accuracy            :", accuracies[gbest_index])
print("Macro F1            :", macro_f1_scores[gbest_index])
print("Selected Features   :", selected_feature_counts[gbest_index])
print("\nBest Feature Mask:")
print(gbest_particle)

velocities = np.zeros((num_particles, num_features))
print(velocities.shape)

np.random.seed(40)

w = 0.7
c1 = 1.5
c2 = 1.5


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


gbest_accuracy = accuracies[gbest_index]
gbest_macro_f1 = macro_f1_scores[gbest_index]
gbest_num_selected = selected_feature_counts[gbest_index]

best_fitness_history = []

for iteration in range(max_iterations):

    for i in range(num_particles):

        r1 = np.random.rand(num_features)
        r2 = np.random.rand(num_features)

        velocities[i] = (
            w * velocities[i]
            + c1 * r1 * (pbest_particles[i] - particles[i])
            + c2 * r2 * (gbest_particle - particles[i])
        )

        probabilities = sigmoid(velocities[i])

        random_values = np.random.rand(num_features)
        particles[i] = (random_values < probabilities).astype(int)

        fitness, accuracy, macro_f1, num_selected = fitness_function(
            particles[i], X_train, X_test, y_train, y_test
        )

        if fitness < pbest_fitness[i]:
            pbest_particles[i] = particles[i].copy()
            pbest_fitness[i] = fitness

        if fitness < gbest_fitness:
            gbest_particle = particles[i].copy()
            gbest_fitness = fitness

            gbest_accuracy = accuracy
            gbest_macro_f1 = macro_f1
            gbest_num_selected = num_selected

    best_fitness_history.append(gbest_fitness)

    print(
        f"Iteration {iteration+1}/{max_iterations} | "
        f"Best Fitness = {gbest_fitness:.4f}"
    )

print("\n========== FINAL PSO RESULT ==========")
print(f"Best Fitness      : {gbest_fitness:.6f}")
print(f"Accuracy          : {gbest_accuracy:.4f}")
print(f"Macro F1          : {gbest_macro_f1:.4f}")
print(f"Selected Features : {gbest_num_selected}")
print("Best Feature Mask :")
print(gbest_particle)

num_whales = 25
num_features = X_train.shape[1]

max_iterations = 100

b = 1

lower_bound = 0.0
upper_bound = 1.0

np.random.seed(42)
positions = np.random.uniform(
low=lower_bound,
high=upper_bound,
size=(num_whales, num_features)
)

leader_position = np.zeros(num_features)
leader_fitness = np.inf
leader_accuracy = 0
leader_macro_f1 = 0
leader_num_features = 0

def binary_conversion(position):
  binary_position = np.where(position > 0.5, 1, 0)
  return binary_position

for i in range(num_whales):
    binary_position = binary_conversion(positions[i])

fitness, accuracy, macro_f1, num_selected = fitness_function(
    binary_position,
    X_train,
    X_test,
    y_train,
    y_test
)

if fitness < leader_fitness:
    leader_fitness = fitness
    leader_position = positions[i].copy()
    leader_accuracy = accuracy
    leader_macro_f1 = macro_f1
    leader_num_features = num_selected

fitness_history = []

for iteration in range(max_iterations):

    a = 2 - (2 * iteration / max_iterations)

    for i in range(num_whales):

        r1 = np.random.rand(num_features)
        r2 = np.random.rand(num_features)

        A = 2 * a * r1 - a
        C = 2 * r2

        p = np.random.rand()

        if p < 0.5:

            if np.linalg.norm(A) < 1:

                D = np.abs(C * leader_position - positions[i])

                new_position = leader_position - A * D

            else:

                random_index = np.random.randint(num_whales)

                random_position = positions[random_index]

                D = np.abs(C * random_position - positions[i])

                new_position = random_position - A * D

        else:

            l = np.random.uniform(-1, 1)

            distance = np.abs(leader_position - positions[i])

            new_position = (
                distance
                * np.exp(b * l)
                * np.cos(2 * np.pi * l)
                + leader_position
            )

        new_position = np.clip(
            new_position,
            lower_bound,
            upper_bound
        )

        positions[i] = new_position

        binary_position = binary_conversion(positions[i])

        fitness, accuracy, macro_f1, num_selected = fitness_function(
            binary_position,
            X_train,
            X_test,
            y_train,
            y_test
        )

        if fitness < leader_fitness:

            leader_fitness = fitness
            leader_position = positions[i].copy()

            leader_accuracy = accuracy
            leader_macro_f1 = macro_f1
            leader_num_features = num_selected

    fitness_history.append(leader_fitness)

    print(
        f"Iteration {iteration+1}/{max_iterations} | "
        f"Best Fitness = {leader_fitness:.4f}"
    )

# -------------------------------
# Final Results
# -------------------------------

best_binary_position = binary_conversion(leader_position)

selected_feature_indices = np.where(best_binary_position == 1)[0]

selected_feature_names = X_train.columns[selected_feature_indices]

print("=" * 50)
print("Binary WOA Completed")
print("=" * 50)

print(f"Best Fitness      : {leader_fitness:.4f}")
print(f"Accuracy          : {leader_accuracy:.4f}")
print(f"Macro F1          : {leader_macro_f1:.4f}")
print(f"Selected Features : {leader_num_features}")

print("\nSelected Feature Names:")

for feature in selected_feature_names:
    print("-", feature)

from matplotlib import pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    range(1, max_iterations + 1),
    fitness_history,
    linewidth=2
)

plt.xlabel("Iteration")
plt.ylabel("Best Fitness")
plt.title("Binary WOA Convergence")
plt.grid(True)

plt.show()

# -------------------------------
# Selected Feature Mask
# -------------------------------

feature_summary = pd.DataFrame({
    "Feature": X_train.columns,
    "Selected": best_binary_position.astype(int)
})

display(feature_summary)

# -------------------------------
# Store Final WOA Results
# -------------------------------

woa_results = {
    "fitness": leader_fitness,
    "accuracy": leader_accuracy,
    "macro_f1": leader_macro_f1,
    "num_features": leader_num_features,
    "feature_mask": best_binary_position,
    "selected_features": list(selected_feature_names),
    "fitness_history": fitness_history
}

print("WOA results stored successfully.")

# -----------------------------------
# Hybrid PSO-WOA Parameters
# -----------------------------------

num_particles = 25
num_features = X_train.shape[1]

max_iterations = 100

# PSO Parameters
w = 0.7
c1 = 2.0
c2 = 2.0

# WOA Parameter
b = 1

# Search Space
lower_bound = 0
upper_bound = 1

np.random.seed(42)

# -----------------------------------
# Initialize Population
# -----------------------------------

positions = np.random.rand(num_particles, num_features)

velocities = np.random.uniform(
    low=-1,
    high=1,
    size=(num_particles, num_features)
)

personal_best_positions = positions.copy()

personal_best_fitness = np.full(num_particles, np.inf)

global_best_position = np.zeros(num_features)
global_best_fitness = np.inf

global_best_accuracy = 0
global_best_macro_f1 = 0
global_best_num_features = 0

# -----------------------------------
# Evaluate Initial Population
# -----------------------------------

for i in range(num_particles):

    binary_position = (positions[i] > 0.5).astype(int)

    fitness, accuracy, macro_f1, num_selected = fitness_function(
        binary_position,
        X_train,
        X_test,
        y_train,
        y_test
    )

    personal_best_fitness[i] = fitness

    if fitness < global_best_fitness:

        global_best_fitness = fitness

        global_best_position = positions[i].copy()

        global_best_accuracy = accuracy

        global_best_macro_f1 = macro_f1

        global_best_num_features = num_selected

# -----------------------------------
# Hybrid PSO-WOA Main Loop
# -----------------------------------

fitness_history = []

for iteration in range(max_iterations):

    a = 2 - (2 * iteration / max_iterations)

    for i in range(num_particles):

        # ===================================
        # PSO Phase
        # ===================================

        r1 = np.random.rand(num_features)
        r2 = np.random.rand(num_features)

        velocities[i] = (
            w * velocities[i]
            + c1 * r1 * (personal_best_positions[i] - positions[i])
            + c2 * r2 * (global_best_position - positions[i])
        )

        positions[i] = positions[i] + velocities[i]

        positions[i] = np.clip(
            positions[i],
            lower_bound,
            upper_bound
        )

        # ===================================
        # WOA Phase
        # ===================================

        r1 = np.random.rand()
        r2 = np.random.rand()

        A = 2 * a * r1 - a
        C = 2 * r2

        p = np.random.rand()

        if p < 0.5:

            if abs(A) < 1:

                D = np.abs(C * global_best_position - positions[i])

                positions[i] = global_best_position - A * D

            else:

                random_index = np.random.randint(num_particles)

                random_position = positions[random_index]

                D = np.abs(C * random_position - positions[i])

                positions[i] = random_position - A * D

        else:

            l = np.random.uniform(-1, 1)

            D = np.abs(global_best_position - positions[i])

            positions[i] = (
                D
                * np.exp(b * l)
                * np.cos(2 * np.pi * l)
                + global_best_position
            )

        positions[i] = np.clip(
            positions[i],
            lower_bound,
            upper_bound
        )

        # ===================================
        # Fitness Evaluation
        # ===================================

        binary_position = (positions[i] > 0.5).astype(int)

        fitness, accuracy, macro_f1, num_selected = fitness_function(
            binary_position,
            X_train,
            X_test,
            y_train,
            y_test
        )

        # ===================================
        # Update Personal Best
        # ===================================

        if fitness < personal_best_fitness[i]:

            personal_best_fitness[i] = fitness

            personal_best_positions[i] = positions[i].copy()

        # ===================================
        # Update Global Best
        # ===================================

        if fitness < global_best_fitness:

            global_best_fitness = fitness

            global_best_position = positions[i].copy()

            global_best_accuracy = accuracy

            global_best_macro_f1 = macro_f1

            global_best_num_features = num_selected

    fitness_history.append(global_best_fitness)

    print(
        f"Iteration {iteration + 1}/{max_iterations} | "
        f"Best Fitness = {global_best_fitness:.4f}"
    )

# -----------------------------------
# Final HPWOA Results
# -----------------------------------

best_binary_position = (global_best_position > 0.5).astype(int)

selected_feature_indices = np.where(best_binary_position == 1)[0]

selected_feature_names = X_train.columns[selected_feature_indices]

print("=" * 50)
print("Hybrid PSO-WOA Completed")
print("=" * 50)

print(f"Best Fitness      : {global_best_fitness:.4f}")
print(f"Accuracy          : {global_best_accuracy:.4f}")
print(f"Macro F1          : {global_best_macro_f1:.4f}")
print(f"Selected Features : {global_best_num_features}")

print("\nSelected Feature Names:")

for feature in selected_feature_names:
    print("-", feature)

# -----------------------------------
# Convergence Plot
# -----------------------------------

plt.figure(figsize=(8,5))

plt.plot(
    range(1, max_iterations + 1),
    fitness_history,
    linewidth=2
)

plt.xlabel("Iteration")
plt.ylabel("Best Fitness")
plt.title("Hybrid PSO-WOA Convergence")
plt.grid(True)

plt.show()

# -----------------------------------
# Feature Selection Summary
# -----------------------------------

feature_summary = pd.DataFrame({
    "Feature": X_train.columns,
    "Selected": best_binary_position
})

display(feature_summary)

# -----------------------------------
# Store Final HPWOA Results
# -----------------------------------

hpwoa_results = {
    "fitness": global_best_fitness,
    "accuracy": global_best_accuracy,
    "macro_f1": global_best_macro_f1,
    "num_features": global_best_num_features,
    "feature_mask": best_binary_position,
    "selected_features": list(selected_feature_names),
    "fitness_history": fitness_history
}

print("Hybrid PSO-WOA results stored successfully.")

"""# **Binary POA**"""

# -----------------------------------
# Binary POA Parameters
# -----------------------------------

num_parrots = 25

num_features = X_train.shape[1]

max_iterations = 100

lower_bound = 0
upper_bound = 1

gamma = 1.5          # Levy flight parameter

np.random.seed(42)
# -----------------------------------
# Initialize Population
# -----------------------------------

positions = np.random.uniform(
    lower_bound,
    upper_bound,
    size=(num_parrots, num_features)
)

best_position = np.zeros(num_features)

best_fitness = np.inf

best_accuracy = 0

best_macro_f1 = 0

best_num_features = 0

fitness_history = []

# -----------------------------------
# Levy Flight Function
# -----------------------------------

from scipy.special import gamma

def levy_flight(dim, beta=1.5):

    sigma = (
        gamma(1 + beta)
        * np.sin(np.pi * beta / 2)
        / (
            gamma((1 + beta) / 2)
            * beta
            * (2 ** ((beta - 1) / 2))
        )
    ) ** (1 / beta)

    u = np.random.normal(0, sigma, dim)
    v = np.random.normal(0, 1, dim)

    step = u / (np.abs(v) ** (1 / beta))

    return step

# -----------------------------------
# Evaluate Initial Population
# -----------------------------------

for i in range(num_parrots):

    binary_position = (positions[i] > 0.5).astype(int)

    fitness, accuracy, macro_f1, num_selected = fitness_function(
        binary_position,
        X_train,
        X_test,
        y_train,
        y_test
    )

    if fitness < best_fitness:

        best_fitness = fitness

        best_position = positions[i].copy()

        best_accuracy = accuracy

        best_macro_f1 = macro_f1

        best_num_features = num_selected

# -----------------------------------
# Binary POA Main Loop
# -----------------------------------

for iteration in range(max_iterations):

    # Population mean (Equation 30)
    mean_position = np.mean(positions, axis=0)

    for i in range(num_parrots):

        current = positions[i].copy()

        # Randomly choose one of four behaviours
        behaviour = np.random.randint(4)

        # -------------------------------------------------
        # 1. FORAGING (Equation 29)
        # -------------------------------------------------

        if behaviour == 0:

            levy = levy_flight(num_features)

            r = np.random.rand()

            decay = (1 - iteration / max_iterations) ** (
                (2 * iteration) / max_iterations
            )

            new_position = (
                (current - best_position) * levy
                + r * decay * mean_position
            )

        # -------------------------------------------------
        # 2. PERCHING (Equation 32)
        # -------------------------------------------------

        elif behaviour == 1:

            levy = levy_flight(num_features)

            new_position = (
                current
                + best_position * levy
                + np.random.rand(num_features)
            )

        # -------------------------------------------------
        # 3. COMMUNICATION (Equation 33)
        # -------------------------------------------------

        elif behaviour == 2:

            P = np.random.rand()

            if P <= 0.5:

                new_position = (
                    0.2
                    * np.random.rand()
                    * (1 - iteration / max_iterations)
                    * (current - mean_position)
                )

            else:

                denominator = (
                    np.random.rand() * max_iterations + 1e-10
                )

                new_position = (
                    0.2
                    * np.random.rand()
                    * np.exp(-iteration / denominator)
                ) * np.ones(num_features)

        # -------------------------------------------------
        # 4. FEAR OF STRANGERS (Equation 34)
        # -------------------------------------------------

        else:

            r1 = np.random.rand()

            r2 = np.random.rand()

            term1 = (
                r1
                * np.cos(
                    0.5
                    * np.pi
                    * iteration
                    / max_iterations
                )
                * (best_position - current)
            )

            term2 = (
                np.cos(r2 * np.pi)
                * (
                    iteration
                    / max_iterations
                ) ** (
                    2 * iteration / max_iterations
                )
                * (current - best_position)
            )

            new_position = current + term1 - term2

        # ---------------------------------------------
        # Keep inside search space
        # ---------------------------------------------

        new_position = np.clip(
            new_position,
            lower_bound,
            upper_bound
        )

        positions[i] = new_position

        # ---------------------------------------------
        # Binary Conversion
        # ---------------------------------------------

        binary_position = (
            positions[i] > 0.5
        ).astype(int)

        fitness, accuracy, macro_f1, num_selected = fitness_function(
            binary_position,
            X_train,
            X_test,
            y_train,
            y_test
        )

        # ---------------------------------------------
        # Update Global Best
        # ---------------------------------------------

        if fitness < best_fitness:

            best_fitness = fitness

            best_position = positions[i].copy()

            best_accuracy = accuracy

            best_macro_f1 = macro_f1

            best_num_features = num_selected

    fitness_history.append(best_fitness)

    print(
        f"Iteration {iteration+1}/{max_iterations} | "
        f"Best Fitness = {best_fitness:.4f}"
    )

# -----------------------------------
# Final Binary POA Results
# -----------------------------------

best_binary_position = (best_position > 0.5).astype(int)

selected_feature_indices = np.where(best_binary_position == 1)[0]

selected_feature_names = X_train.columns[selected_feature_indices]

print("=" * 50)
print("Binary POA Completed")
print("=" * 50)

print(f"Best Fitness      : {best_fitness:.4f}")
print(f"Accuracy          : {best_accuracy:.4f}")
print(f"Macro F1          : {best_macro_f1:.4f}")
print(f"Selected Features : {best_num_features}")

print("\nSelected Feature Names:")

for feature in selected_feature_names:
    print("-", feature)

"""# **Hybrid PSO POA**"""

# -----------------------------------
# Hybrid PSO-POA Parameters
# -----------------------------------

num_particles = 25

num_features = X_train.shape[1]

max_iterations = 100

# PSO Parameters
w = 0.7
c1 = 2.0
c2 = 2.0

# Levy Flight Parameter
gamma = 1.5

lower_bound = 0
upper_bound = 1

np.random.seed(42)

# -----------------------------------
# Initialize Population
# -----------------------------------

positions = np.random.uniform(
    lower_bound,
    upper_bound,
    size=(num_particles, num_features)
)

velocities = np.random.uniform(
    -1,
    1,
    size=(num_particles, num_features)
)

personal_best_positions = positions.copy()

personal_best_fitness = np.full(
    num_particles,
    np.inf
)

global_best_position = np.zeros(num_features)

global_best_fitness = np.inf

global_best_accuracy = 0

global_best_macro_f1 = 0

global_best_num_features = 0

fitness_history = []

# -----------------------------------
# Levy Flight Function
# -----------------------------------

from scipy.special import gamma

def levy_flight(dim, beta=1.5):

    sigma = (
        gamma(1 + beta)
        * np.sin(np.pi * beta / 2)
        /
        (
            gamma((1 + beta) / 2)
            * beta
            * (2 ** ((beta - 1) / 2))
        )
    ) ** (1 / beta)

    u = np.random.normal(
        0,
        sigma,
        dim
    )

    v = np.random.normal(
        0,
        1,
        dim
    )

    step = u / (np.abs(v) ** (1 / beta))

    return step

# -----------------------------------
# Evaluate Initial Population
# -----------------------------------

for i in range(num_particles):

    binary_position = (
        positions[i] > 0.5
    ).astype(int)

    fitness, accuracy, macro_f1, num_selected = fitness_function(
        binary_position,
        X_train,
        X_test,
        y_train,
        y_test
    )

    personal_best_fitness[i] = fitness

    if fitness < global_best_fitness:

        global_best_fitness = fitness

        global_best_position = positions[i].copy()

        global_best_accuracy = accuracy

        global_best_macro_f1 = macro_f1

        global_best_num_features = num_selected

# -----------------------------------
# Hybrid PSO-POA Main Loop (Staged)
# -----------------------------------

pso_iterations = 60

for iteration in range(max_iterations):

    mean_position = np.mean(positions, axis=0)

    for i in range(num_particles):

        # =====================================================
        # PHASE 1 : PSO Exploration
        # =====================================================

        if iteration < pso_iterations:

            r1 = np.random.rand(num_features)
            r2 = np.random.rand(num_features)

            velocities[i] = (
                w * velocities[i]
                + c1 * r1 * (personal_best_positions[i] - positions[i])
                + c2 * r2 * (global_best_position - positions[i])
            )

            positions[i] += velocities[i]

        # =====================================================
        # PHASE 2 : POA Refinement
        # =====================================================

        else:

            current = positions[i].copy()

            behaviour = np.random.randint(4)

            # -----------------------
            # Foraging
            # -----------------------

            if behaviour == 0:

                levy = levy_flight(num_features)

                r = np.random.rand()

                decay = (
                    1 - iteration / max_iterations
                ) ** (
                    (2 * iteration) / max_iterations
                )

                current = (
                    (current - global_best_position)
                    * levy
                    + r * decay * mean_position
                )

            # -----------------------
            # Perching
            # -----------------------

            elif behaviour == 1:

                levy = levy_flight(num_features)

                current = (
                    current
                    + global_best_position * levy
                    + np.random.rand(num_features)
                )

            # -----------------------
            # Communication
            # -----------------------

            elif behaviour == 2:

                P = np.random.rand()

                if P <= 0.5:

                    current = (
                        0.2
                        * np.random.rand()
                        * (1 - iteration / max_iterations)
                        * (current - mean_position)
                    )

                else:

                    current = (
                        0.2
                        * np.random.rand()
                        * np.exp(
                            -iteration /
                            (
                                np.random.rand()
                                * max_iterations
                                + 1e-10
                            )
                        )
                    ) * np.ones(num_features)

            # -----------------------
            # Fear of Strangers
            # -----------------------

            else:

                r1 = np.random.rand()
                r2 = np.random.rand()

                current = (
                    current
                    + r1
                    * np.cos(
                        0.5
                        * np.pi
                        * iteration
                        / max_iterations
                    )
                    * (
                        global_best_position
                        - current
                    )
                    - np.cos(r2 * np.pi)
                    * (
                        iteration
                        / max_iterations
                    ) ** (
                        2 * iteration
                        / max_iterations
                    )
                    * (
                        current
                        - global_best_position
                    )
                )

            positions[i] = current

        # =====================================================
        # Common Part
        # =====================================================

        positions[i] = np.clip(
            positions[i],
            lower_bound,
            upper_bound
        )

        binary_position = (
            positions[i] > 0.5
        ).astype(int)

        fitness, accuracy, macro_f1, num_selected = fitness_function(
            binary_position,
            X_train,
            X_test,
            y_train,
            y_test
        )

        if fitness < personal_best_fitness[i]:

            personal_best_fitness[i] = fitness
            personal_best_positions[i] = positions[i].copy()

        if fitness < global_best_fitness:

            global_best_fitness = fitness
            global_best_position = positions[i].copy()
            global_best_accuracy = accuracy
            global_best_macro_f1 = macro_f1
            global_best_num_features = num_selected

    fitness_history.append(global_best_fitness)

    print(
        f"Iteration {iteration+1}/{max_iterations} | "
        f"Best Fitness = {global_best_fitness:.4f}"
    )

# -----------------------------------
# Final Hybrid PSO-POA Results
# -----------------------------------

best_binary_position = (global_best_position > 0.5).astype(int)

selected_feature_indices = np.where(best_binary_position == 1)[0]

selected_feature_names = X_train.columns[selected_feature_indices]

print("=" * 50)
print("Hybrid PSO-POA Completed")
print("=" * 50)

print(f"Best Fitness      : {global_best_fitness:.4f}")
print(f"Accuracy          : {global_best_accuracy:.4f}")
print(f"Macro F1          : {global_best_macro_f1:.4f}")
print(f"Selected Features : {global_best_num_features}")

print("\nSelected Feature Names:")

for feature in selected_feature_names:
    print("-", feature)

# -----------------------------------
# Convergence Plot
# -----------------------------------

plt.figure(figsize=(8,5))

plt.plot(
    range(1, max_iterations + 1),
    fitness_history,
    linewidth=2
)

plt.xlabel("Iteration")
plt.ylabel("Best Fitness")
plt.title("Hybrid PSO-POA Convergence")
plt.grid(True)

plt.show()

# -----------------------------------
# Feature Selection Summary
# -----------------------------------

feature_summary = pd.DataFrame({
    "Feature": X_train.columns,
    "Selected": best_binary_position
})

display(feature_summary)

# -----------------------------------
# Store Final HPPOA Results
# -----------------------------------

hppoa_results = {
    "fitness": global_best_fitness,
    "accuracy": global_best_accuracy,
    "macro_f1": global_best_macro_f1,
    "num_features": global_best_num_features,
    "feature_mask": best_binary_position,
    "selected_features": list(selected_feature_names),
    "fitness_history": fitness_history
}

print("Hybrid PSO-POA results stored successfully.")

"""# **Adaptive PSO POA**"""

# -----------------------------------
# Adaptive PSO-POA Parameters
# -----------------------------------

num_particles = 25

num_features = X_train.shape[1]

max_iterations = 100

# PSO Parameters
w = 0.7
c1 = 2.0
c2 = 2.0

# POA Parameter
gamma = 1.5

# Search Space
lower_bound = 0
upper_bound = 1

# Mutation Parameters
stagnation_limit = 10

np.random.seed(42)

# -----------------------------------
# Initialize Population
# -----------------------------------

positions = np.random.rand(
    num_particles,
    num_features
)

velocities = np.random.uniform(
    -1,
    1,
    size=(num_particles, num_features)
)

personal_best_positions = positions.copy()

personal_best_fitness = np.full(
    num_particles,
    np.inf
)

global_best_position = np.zeros(num_features)

global_best_fitness = np.inf

global_best_accuracy = 0
global_best_macro_f1 = 0
global_best_num_features = 0

fitness_history = []

# Counts consecutive iterations
# where a particle fails to improve
stagnation_counter = np.zeros(
    num_particles,
    dtype=int
)

# -----------------------------------
# Levy Flight Function
# -----------------------------------

from scipy.special import gamma

def levy_flight(dim, beta=1.5):

    sigma = (
        gamma(1 + beta)
        * np.sin(np.pi * beta / 2)
        /
        (
            gamma((1 + beta) / 2)
            * beta
            * (2 ** ((beta - 1) / 2))
        )
    ) ** (1 / beta)

    u = np.random.normal(0, sigma, dim)

    v = np.random.normal(0, 1, dim)

    return u / (np.abs(v) ** (1 / beta))



# -----------------------------------
# Evaluate Initial Population
# -----------------------------------

for i in range(num_particles):

    binary_position = (
        positions[i] > 0.5
    ).astype(int)

    fitness, accuracy, macro_f1, num_selected = fitness_function(
        binary_position,
        X_train,
        X_test,
        y_train,
        y_test
    )

    personal_best_fitness[i] = fitness

    if fitness < global_best_fitness:

        global_best_fitness = fitness

        global_best_position = positions[i].copy()

        global_best_accuracy = accuracy

        global_best_macro_f1 = macro_f1

        global_best_num_features = num_selected

# -----------------------------------
# Adaptive PSO + POA Main Loop
# -----------------------------------

for iteration in range(max_iterations):

    mean_position = np.mean(positions, axis=0)

    for i in range(num_particles):

        # ==========================================
        # Save Current Position
        # ==========================================

        original_position = positions[i].copy()

        # ==========================================
        # Standard PSO Update
        # ==========================================

        r1 = np.random.rand(num_features)
        r2 = np.random.rand(num_features)

        velocities[i] = (
            w * velocities[i]
            + c1 * r1 * (personal_best_positions[i] - positions[i])
            + c2 * r2 * (global_best_position - positions[i])
        )

        positions[i] += velocities[i]

        positions[i] = np.clip(
            positions[i],
            lower_bound,
            upper_bound
        )

        # ==========================================
        # Evaluate PSO Position
        # ==========================================

        binary_position = (
            positions[i] > 0.5
        ).astype(int)

        fitness, accuracy, macro_f1, num_selected = fitness_function(
            binary_position,
            X_train,
            X_test,
            y_train,
            y_test
        )

        # ==========================================
        # Update Personal Best
        # ==========================================

        if fitness < personal_best_fitness[i]:

            personal_best_fitness[i] = fitness

            personal_best_positions[i] = positions[i].copy()

            stagnation_counter[i] = 0

        else:

            stagnation_counter[i] += 1

        # ==========================================
        # Apply POA Mutation if Particle Stagnates
        # ==========================================

        if stagnation_counter[i] >= stagnation_limit:

            mutated_position = positions[i].copy()

            behaviour = np.random.randint(2)

            # --------------------------------------
            # Behaviour 1 : Foraging
            # --------------------------------------

            if behaviour == 0:

                levy = levy_flight(num_features)

                mutated_position += (
                    0.30
                    * levy
                    * (global_best_position - mutated_position)
                )

            # --------------------------------------
            # Behaviour 2 : Fear of Strangers
            # --------------------------------------

            else:

                mutated_position += (
                    0.20
                    * np.cos(
                        np.random.rand() * np.pi
                    )
                    * (
                        global_best_position
                        - mutated_position
                    )
                )

            mutated_position = np.clip(
                mutated_position,
                lower_bound,
                upper_bound
            )

            # ======================================
            # Evaluate Mutated Position
            # ======================================

            binary_mutation = (
                mutated_position > 0.5
            ).astype(int)

            mutation_fitness, mutation_accuracy, mutation_macro_f1, mutation_features = fitness_function(
                binary_mutation,
                X_train,
                X_test,
                y_train,
                y_test
            )

            # ======================================
            # Accept Mutation Only if Better
            # ======================================

            if mutation_fitness < fitness:

                positions[i] = mutated_position

                fitness = mutation_fitness
                accuracy = mutation_accuracy
                macro_f1 = mutation_macro_f1
                num_selected = mutation_features

                personal_best_fitness[i] = mutation_fitness
                personal_best_positions[i] = mutated_position.copy()

                stagnation_counter[i] = 0

            else:

                positions[i] = original_position

        # ==========================================
        # Update Global Best
        # ==========================================

        if fitness < global_best_fitness:

            global_best_fitness = fitness

            global_best_position = positions[i].copy()

            global_best_accuracy = accuracy

            global_best_macro_f1 = macro_f1

            global_best_num_features = num_selected

    fitness_history.append(global_best_fitness)

    print(
        f"Iteration {iteration+1}/{max_iterations} | "
        f"Best Fitness = {global_best_fitness:.4f}"
    )

# -----------------------------------
# Final Adaptive PSO-POA Results
# -----------------------------------

best_binary_position = (global_best_position > 0.5).astype(int)

selected_feature_indices = np.where(best_binary_position == 1)[0]

selected_feature_names = X_train.columns[selected_feature_indices]

print("=" * 50)
print("Adaptive PSO-POA Completed")
print("=" * 50)

print(f"Best Fitness      : {global_best_fitness:.4f}")
print(f"Accuracy          : {global_best_accuracy:.4f}")
print(f"Macro F1          : {global_best_macro_f1:.4f}")
print(f"Selected Features : {global_best_num_features}")

print("\nSelected Feature Names:")

for feature in selected_feature_names:
    print("-", feature)

"""# **Optimizing POA**"""

